name: Build the Digital Land map

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

env:
  GITHUB_ACTOR_EMAIL: ${{ secrets.GITHUB_ACTOR_EMAIL }}
  GITHUB_ACTOR_TOKEN: ${{ secrets.GITHUB_ACTOR_TOKEN }}
  GITHUB_ACTOR_USERNAME: ${{ secrets.GITHUB_ACTOR_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages
        run: npm install
      - name: Refresh submodules
        run: npm run refresh
      - name: Generate map script
        run: npm run compile
      - name: Update repository with new data sources and a new map
        run: |
          git config user.email "${GITHUB_ACTOR_EMAIL}"
          git config user.name "${GITHUB_ACTOR_USERNAME}"
          git remote set-url origin https://${GITHUB_ACTOR_USERNAME}:${GITHUB_ACTOR_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update map for $(date +%F)"; git push origin master)
